[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
test_anchor_2 = "PhaARiQBd8a2AcH239Hzf84EM3KLNP1JGEP9CUeZfvE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
